global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # # The job name is added as a label `job=<job_name>` to any timeseries scra    ped from this config.
  # - job_name: 'prometheus'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['localhost:9090']

  # Node exporter
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']

  # Docker daemon
  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:9323']

  # # FRR exporter
  # - job_name: frr
  #   static_configs:
  #     - targets:
  #       - device1:9342
  #       - device2:9342
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       regex: "(.*):\d+"
  #       target: instance